# base_template.yml

parameters:
- name: NX_BRANCH 
  type: string
  default: "" # defaults for any parameters
- name: TARGET_BRANCH
  type: string
  default: ""
- name: BASE_SHA
  type: string
  default: ""
- name: HEAD_SHA
  type: string
  default: ""
- name: pnpm_config_cache
  type: string
  default: ""


jobs:
  - job: Setup_CI_And_Dependencies
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - checkout: self
        fetchDepth: 0
      # Set Azure Devops CLI default settings
      - bash: az devops configure --defaults organization=$(System.TeamFoundationCollectionUri) project=$(System.TeamProject)
        displayName: 'Set default Azure DevOps organization and project'
      # Get last successfull commit from Azure Devops CLI
      - bash: |
          LAST_SHA=$(az pipelines build list --branch $(Build.SourceBranchName) --definition-ids $(System.DefinitionId) --result succeeded --top 1 --query "[0].triggerInfo.\"ci.sourceSha\"")
          if [ -z "$LAST_SHA" ]
          then
            echo "Last successful commit not found. Using fallback 'HEAD~1': $parameters.BASE_SHA"
          else
            echo "Last successful commit SHA: $LAST_SHA"
            echo "##vso[task.setvariable variable=parameters.BASE_SHA]$LAST_SHA"
          fi
        displayName: 'Get last successful commit SHA'
        condition: ne(variables['Build.Reason'], 'PullRequest')
        env:
          AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)

      - task: Cache@2
        inputs:
          key: '"$(Agent.OS)" | pnpm-lock.yaml'
          path: $(pnpm_config_cache)
          restoreKeys: |
             pnpm |  "$(Agent.OS)"
        displayName: Cache pnpm
        continueOnError: true
      
      - script: |
         npm install --prefix=$HOME/.local -g pnpm@9.7.1 
         pnpm config set store-dir $(pnpm_config_cache)
        displayName: Install PNPM

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      - script: pnpm dlx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

      - script: pnpm install --frozen-lockfile
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: 'cp -LR node_modules tmp && rm -rf node_modules && mv tmp node_modules'
    
      - script: git branch --track main origin/main
        condition: eq(variables['Build.Reason'], 'PullRequest')

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      - script: pnpm exec nx-cloud record -- echo Starting To Build Apps.
      # Nx Affected runs only tasks affected by the changes in this PR/commit. Learn more: https://nx.dev/ci/features/affected
      # Not working - script: pnpm exec nx affected --base=$(parameters.BASE_SHA) --head=$(parameters.HEAD_SHA) lint test build
      
      # Upload assets to pipeline artifacts so its accessible by other pipelines
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: 'node_modules'
          artifact: 'node_modules'
          publishLocation: 'pipeline'
      
