# This pipeline runs whenever there are changes inside of the apps/shell project
# We also only want this pipeline to run after the base pipeline runs 
trigger:
  paths:
    include:
    - apps/shell/**


resources:
  pipelines:
    - pipeline: basepipeline
      source: base-pipeline
      
pool:
  vmImage: ubuntu-latest


jobs:
- job: BuildShell
  steps:
    - script: |
        curl -X POST \
         -u $(System.AccessToken): \
         -H "Content-Type: application/json" \
         -d '{"resources": {"repositories": {"self": {"refName": "refs/heads/main"}}}}' \
         https://dev.azure.com/xdevrspace/Federated_App_Deployments/_apis/pipelines/shell-deployment-pipeline/runs?api-version=7.1-preview.1
      # condition: and(succeeded(), containsValue(variables['Build.SourceVersionPaths'], 'apps/shell'))
        

