# This pipeline runs whenever there are changes inside of the apps/shell project
# We also only want this pipeline to run after the base pipeline runs 
trigger:
  paths:
    include:
    - apps/shell/**

variables:
  CI: 'true'
  ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
    NX_BRANCH: $(System.PullRequest.PullRequestNumber)
    TARGET_BRANCH: $[replace(variables['System.PullRequest.TargetBranch'],'refs/heads/','origin/')]
    BASE_SHA: $(git merge-base $(TARGET_BRANCH) HEAD)
  ${{ if ne(variables['Build.Reason'], 'PullRequest') }}:
    NX_BRANCH: $(Build.SourceBranchName)
    BASE_SHA: $(git rev-parse HEAD~1)
  HEAD_SHA: $(git rev-parse HEAD)

      
pool:
  vmImage: ubuntu-latest

stages:
- stage: BundleDependencies
  jobs:
  - template: base_template.yml
    parameters:
      NX_BRANCH: NX_BRANCH
      TARGET_BRANCH: TARGET_BRANCH
      BASE_SHA: BASE_SHA
      HEAD_SHA: HEAD_SHA

- stage: Build_Shell
  jobs: 
   - job: Execute_Nx_Build
     steps:
      - task: DownloadPipelineArtifact@2
        inputs:
          buildType: 'current'
          artifactName: 'node_modules'
          targetPath: '$(Pipeline.Workspace)'
      - script: pnpx nx build shell


