# This pipeline runs whenever there are changes inside of the apps/shell project
# We also only want this pipeline to run after the base pipeline runs 
trigger:
  paths:
    include:
    - apps/shell/**


resources:
  pipelines:
    - pipeline: basepipeline
      source: base-pipeline
      
pool:
  vmImage: ubuntu-latest


jobs:
- job: BuildShell
  steps:
    - script: |
        # Setting a variable based on what project has had file changes
        condition: and(containsValue(variables['Build.SourceVersionPaths'], 'apps/shell')
        echo "Hello world"

