# This pipeline runs whenever there are changes inside of the apps/shell project
# We also only want this pipeline to run after the base pipeline runs 
trigger:
  paths:
    include:
    - apps/shell/**


resources:
  pipelines:
    - pipeline: basepipeline
      source: base-pipeline
      
pool:
  vmImage: ubuntu-latest


jobs:
- job: BuildShell
  steps:
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

